---
collections:
  - name: cisco.ios
  - name: community.network
  - name: dellemc.os10
  - name: ansible.netcommon
    version: "8.0.0"
  - name: ansible.utils
    version: "5.0.0"
  - name: ansible.network


