# playbooks/test_connect_planet.yml
---
- name: Testar conexão SSH e coletar informações do switch Planet
  hosts: sw-teste
  gather_facts: no

  vars:
    ansible_connection: ssh

  tasks:
    - name: Mostrar nome do host e IP
      debug:
        msg: "Conectando em {{ inventory_hostname }} ({{ ansible_host }})"

    - name: Verificação de acesso CLI (comando Planet)
      raw: "show system"
      register: output

    - name: Exibir saída
      debug:
        var: output.stdout
