# inventory/group_vars/all.yml
ansible_connection: paramiko_ssh
ansible_user: admin
ansible_password: cpdscm
ansible_network_os: none
ansible_shell_type: raw
ansible_shell_executable: "/bin/sh"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa"

# Timeout e logs
timeout: 20
log_path: /var/log/ansible/network.log

# DNS padrão (caso não definido no host)
dns_servers:
  - 172.16.30.0
  - 172.16.30.2

# SNMP padrão (pode ser sobrescrito em cada host)
snmp_version: 2c
snmp_community: public
snmp_port: 161
